
services:
  auth-api:
    image: auth-api:1.0
    ports:
      - "9000:9000" # 훾itamo varijablu okru탑enja PORT iz .env datoteke
    env_file:
      - .env # u훾itavamo varijable okru탑enja iz .env datoteke
    networks:
      - interna_mreza

  social-api:
    image: social-api:1.0
    ports:
      - "3500:3500"
    networks:
      - interna_mreza

networks:
  interna_mreza:
    driver: bridge
